#!/usr/bin/env bash
set -euo pipefail

# SilentSuite Self-Hosted Installer
# -----------------------------------
# Sets up the SilentSuite sync server with PostgreSQL.
# You provide your own reverse proxy for TLS.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

echo "============================================"
echo "  SilentSuite Self-Hosted Installer"
echo "============================================"
echo ""

# ── Prerequisites ──────────────────────────────────────────────────────

check_command() {
  if ! command -v "$1" &>/dev/null; then
    echo "ERROR: '$1' is not installed. Please install it first."
    exit 1
  fi
}

check_command docker
check_command openssl

if docker compose version &>/dev/null; then
  COMPOSE="docker compose"
elif command -v docker-compose &>/dev/null; then
  COMPOSE="docker-compose"
else
  echo "ERROR: 'docker compose' is not available. Please install Docker Compose v2."
  exit 1
fi

echo "Prerequisites OK: docker, $COMPOSE, openssl"
echo ""

# ── Clean up stale containers ─────────────────────────────────────────

for container in silentsuite-postgres silentsuite-server; do
  if docker inspect "$container" &>/dev/null; then
    echo "Removing stale container: $container"
    docker stop "$container" 2>/dev/null || true
    docker rm "$container" 2>/dev/null || true
  fi
done

# ── Gather configuration ──────────────────────────────────────────────

if [ -f .env ]; then
  echo "An existing .env file was found."
  read -rp "Overwrite it? (y/N): " OVERWRITE
  if [[ ! "$OVERWRITE" =~ ^[Yy]$ ]]; then
    echo "Keeping existing .env. Starting containers..."
    $COMPOSE pull
    $COMPOSE up -d
    echo ""
    echo "Done. Run ./verify.sh to check health."
    exit 0
  fi
fi

echo "Enter the domain name your server will be accessible at."
echo "This is the hostname users will enter in the SilentSuite app."
echo "Examples: sync.example.com, silentsuite.example.com"
echo ""
read -rp "Domain: " DOMAIN

if [ -z "$DOMAIN" ]; then
  echo "ERROR: Domain cannot be empty."
  exit 1
fi

echo ""

# ── Generate passwords ────────────────────────────────────────────────

echo "Generating secure passwords..."
DATABASE_PASSWORD=$(openssl rand -base64 32 | tr -d '/+=')
SUPER_PASS=$(openssl rand -base64 16 | tr -d '/+=')

# ── Write .env ─────────────────────────────────────────────────────────

cat > .env <<EOF
# SilentSuite Self-Hosted Configuration
# Generated by install.sh on $(date -u +"%Y-%m-%d %H:%M UTC")

# Port the SilentSuite server listens on (default: 3735).
# Your reverse proxy should forward traffic to this port.
SERVER_PORT=3735

# PostgreSQL credentials (auto-generated)
DATABASE_PASSWORD=$DATABASE_PASSWORD

# Admin credentials for the admin panel at https://$DOMAIN/admin/
SUPER_USER=admin
SUPER_PASS=$SUPER_PASS

# Comma-separated list of hostnames the server will accept.
# Must include your domain. Add localhost if you also want local access.
ALLOWED_HOSTS=$DOMAIN,localhost
EOF

chmod 600 .env
echo "Wrote .env (permissions: 600)"

# ── Pull images and start ─────────────────────────────────────────────

echo ""
echo "Pulling images and starting containers..."
$COMPOSE pull
$COMPOSE up -d

# ── Wait for health checks ───────────────────────────────────────────

echo ""
echo "Waiting for services to become healthy..."

MAX_WAIT=120
ELAPSED=0
while [ $ELAPSED -lt $MAX_WAIT ]; do
  HEALTHY=0

  for container in silentsuite-postgres silentsuite-server; do
    status=$(docker inspect --format='{{.State.Health.Status}}' "$container" 2>/dev/null || echo "unknown")
    if [ "$status" = "healthy" ]; then
      HEALTHY=$((HEALTHY + 1))
    fi
  done

  if [ "$HEALTHY" -ge 2 ]; then
    break
  fi

  sleep 5
  ELAPSED=$((ELAPSED + 5))
  echo "  $HEALTHY/2 services healthy ($ELAPSED/${MAX_WAIT}s)..."
done

if [ "$HEALTHY" -lt 2 ]; then
  echo ""
  echo "WARNING: Not all services are healthy after ${MAX_WAIT}s."
  echo "Run '$COMPOSE logs' to troubleshoot."
  echo ""
fi

echo ""
echo "============================================"
echo "  SilentSuite is installed!"
echo "============================================"
echo ""
echo "  Server:        http://localhost:3735 (internal)"
echo "  Public URL:    https://$DOMAIN (after reverse proxy setup)"
echo "  Admin Panel:   https://$DOMAIN/admin/"
echo ""
echo "  Admin user:    admin"
echo "  Admin pass:    $SUPER_PASS"
echo ""
echo "  IMPORTANT: Save these credentials!"
echo "  They are also stored in .env"
echo ""
echo "  Next steps:"
echo "  1. Set up your reverse proxy to forward HTTPS traffic"
echo "     to localhost:3735"
echo "     (Caddy, nginx, Traefik, or Cloudflare Tunnel)"
echo ""
echo "  2. Make sure your DNS A record for $DOMAIN"
echo "     points to this server's public IP"
echo ""
echo "  3. Open https://app.silentsuite.io (or the mobile app)"
echo "  4. On the signup page, expand 'Advanced Settings'"
echo "  5. Enter https://$DOMAIN as the server URL"
echo "  6. Create your account and start syncing!"
echo ""
