#!/usr/bin/env bash
set -euo pipefail

# SilentSuite Self-Hosted Installer
# -----------------------------------
# Sets up the SilentSuite sync server with PostgreSQL.
# Can be run standalone via:
#   curl -fsSL https://raw.githubusercontent.com/silent-suite/silentsuite/main/self-host/install.sh | bash

GITHUB_RAW_BASE="https://raw.githubusercontent.com/silent-suite/silentsuite/main/self-host"
INSTALL_DIR="${SILENTSUITE_DIR:-silentsuite-server}"

echo "============================================"
echo "  SilentSuite Self-Hosted Installer"
echo "============================================"
echo ""

# ── Prerequisites ──────────────────────────────────────────────────────

check_command() {
  if ! command -v "$1" &>/dev/null; then
    echo "ERROR: '$1' is not installed. Please install it first."
    exit 1
  fi
}

check_command docker
check_command openssl
check_command curl

if docker compose version &>/dev/null; then
  COMPOSE="docker compose"
elif command -v docker-compose &>/dev/null; then
  COMPOSE="docker-compose"
else
  echo "ERROR: 'docker compose' is not available. Please install Docker Compose v2."
  exit 1
fi

echo "Prerequisites OK: docker, $COMPOSE, openssl, curl"
echo ""

# ── Set up install directory ──────────────────────────────────────────

if [ ! -d "$INSTALL_DIR" ]; then
  echo "Creating install directory: $INSTALL_DIR"
  mkdir -p "$INSTALL_DIR"
fi
cd "$INSTALL_DIR"

# ── Download docker-compose.yml ───────────────────────────────────────

echo "Downloading docker-compose.yml..."
curl -fsSL "$GITHUB_RAW_BASE/docker-compose.yml" -o docker-compose.yml

# ── Download helper scripts ───────────────────────────────────────────

for script in update.sh verify.sh; do
  echo "Downloading $script..."
  curl -fsSL "$GITHUB_RAW_BASE/$script" -o "$script"
  chmod +x "$script"
done

echo "Downloading landing page..."
curl -fsSL "$GITHUB_RAW_BASE/success.html" -o success.html

echo ""

# ── Clean up stale containers ─────────────────────────────────────────

for container in silentsuite-postgres silentsuite-server; do
  if docker inspect "$container" &>/dev/null; then
    echo "Removing stale container: $container"
    docker stop "$container" 2>/dev/null || true
    docker rm "$container" 2>/dev/null || true
  fi
done

# ── Gather configuration ──────────────────────────────────────────────

if [ -f .env ]; then
  echo "An existing .env file was found."
  read -rp "Overwrite it? (y/N): " OVERWRITE </dev/tty
  if [[ ! "$OVERWRITE" =~ ^[Yy]$ ]]; then
    echo "Keeping existing .env. Starting containers..."
    $COMPOSE pull
    $COMPOSE up -d
    echo ""
    echo "Done. Run ./verify.sh to check health."
    exit 0
  fi
fi

echo "Enter the domain name your server will be accessible at."
echo "This is the hostname users will enter in the SilentSuite app."
echo "Examples: sync.example.com, silentsuite.example.com"
echo ""
read -rp "Domain: " DOMAIN </dev/tty

if [ -z "$DOMAIN" ]; then
  echo "ERROR: Domain cannot be empty."
  exit 1
fi

echo ""
echo "If you're using a Docker-based reverse proxy (Nginx Proxy Manager, Traefik),"
echo "enter the Docker network name it runs on (leave empty to skip):"
echo ""
read -rp "Proxy network name [empty to skip]: " PROXY_NETWORK </dev/tty
echo ""

# ── Generate passwords ────────────────────────────────────────────────

echo "Generating secure passwords..."
DATABASE_PASSWORD=$(openssl rand -base64 32 | tr -d '/+=')
SUPER_PASS=$(openssl rand -base64 16 | tr -d '/+=')

# ── Write .env ─────────────────────────────────────────────────────────

cat > .env <<EOF
# SilentSuite Self-Hosted Configuration
# Generated by install.sh on $(date -u +"%Y-%m-%d %H:%M UTC")

# Port the SilentSuite server listens on (default: 3735).
# Your reverse proxy should forward traffic to this port.
SERVER_PORT=3735

# PostgreSQL credentials (auto-generated)
DATABASE_PASSWORD=$DATABASE_PASSWORD

# Django admin panel credentials (advanced use only).
# These are for the Etebase Django admin at https://$DOMAIN/admin/
# Most users don't need this — the first user to sign up in the
# SilentSuite app becomes the server admin automatically.
SUPER_USER=admin
SUPER_PASS=$SUPER_PASS

# Comma-separated list of hostnames the server will accept.
# Must include your domain. Add localhost if you also want local access.
ALLOWED_HOSTS=$DOMAIN,localhost
EOF

chmod 600 .env

# ── Proxy network override ─────────────────────────────────────────────

if [ -n "$PROXY_NETWORK" ]; then
  echo "PROXY_NETWORK=$PROXY_NETWORK" >> .env
  cat > docker-compose.override.yml <<OVERRIDE
# Auto-generated: connects the server to your reverse proxy network.
# Delete this file if you no longer need proxy network integration.
services:
  server:
    networks:
      - silentsuite
      - proxy

networks:
  silentsuite:
    driver: bridge
  proxy:
    external: true
    name: $PROXY_NETWORK
OVERRIDE
  echo "Generated docker-compose.override.yml for proxy network: $PROXY_NETWORK"
fi

# ── Generate etebase-server.ini ────────────────────────────────────────

cat > etebase-server.ini <<INIEOF
; SilentSuite / Etebase server configuration
; Generated by install.sh on $(date -u +"%Y-%m-%d %H:%M UTC")
;
; This file is mounted into the container and takes precedence over
; environment variables. Edit it and restart to apply changes:
;   docker compose restart server

[global]
secret_file = /data/secret.txt
debug = false

[allowed_hosts]
allowed_host1 = $DOMAIN
allowed_host2 = localhost

[database]
engine = postgres
name = silentsuite
user = silentsuite
password = $DATABASE_PASSWORD
host = postgres
port = 5432
INIEOF
chmod 600 etebase-server.ini
echo "Generated etebase-server.ini"

echo "Wrote .env (permissions: 600)"

# ── Pull images and start ─────────────────────────────────────────────

echo ""
echo "Pulling images and starting containers..."
$COMPOSE pull
$COMPOSE up -d

# ── Wait for health checks ───────────────────────────────────────────

echo ""
echo "Waiting for services to become healthy..."

MAX_WAIT=120
ELAPSED=0
while [ $ELAPSED -lt $MAX_WAIT ]; do
  HEALTHY=0

  for container in silentsuite-postgres silentsuite-server; do
    status=$(docker inspect --format='{{.State.Health.Status}}' "$container" 2>/dev/null || echo "unknown")
    if [ "$status" = "healthy" ]; then
      HEALTHY=$((HEALTHY + 1))
    fi
  done

  if [ "$HEALTHY" -ge 2 ]; then
    break
  fi

  sleep 5
  ELAPSED=$((ELAPSED + 5))
  echo "  $HEALTHY/2 services healthy ($ELAPSED/${MAX_WAIT}s)..."
done

if [ "$HEALTHY" -lt 2 ]; then
  echo ""
  echo "WARNING: Not all services are healthy after ${MAX_WAIT}s."
  echo "Run '$COMPOSE logs' to troubleshoot."
  echo ""
fi

echo ""
echo "============================================"
echo "  SilentSuite is installed!"
echo "============================================"
echo ""
echo "  The first user to sign up becomes the server admin."
echo ""
echo "  Next steps:"
echo ""
echo "  1. Set up a reverse proxy to forward HTTPS traffic"
echo "     to this server on port 3735."
echo ""
echo "     The server listens on 127.0.0.1:3735 (localhost only)."
echo "     You need a reverse proxy (Caddy, nginx, Traefik, or"
echo "     Cloudflare Tunnel) to handle TLS and forward traffic."
echo ""
if [ -n "$PROXY_NETWORK" ]; then
echo "     Your reverse proxy network ($PROXY_NETWORK) has been"
echo "     configured. Use 'silentsuite-server:3735' as the"
echo "     upstream/target in your proxy settings."
else
echo "     If using Nginx Proxy Manager or another Docker-based proxy,"
echo "     re-run this installer and enter the proxy network name, or"
echo "     manually connect the containers:"
echo "       docker network connect <proxy_network> silentsuite-server"
echo "     Then use 'silentsuite-server:3735' as the upstream."
fi
echo ""
echo "  2. Point your DNS A record for $DOMAIN"
echo "     to this server's public IP."
echo ""
echo "  3. Open https://app.silentsuite.io (or the mobile app)"
echo "  4. On the signup page, expand 'Advanced Settings'"
echo "  5. Enter https://$DOMAIN as the server URL"
echo "  6. Create your account — you'll be the admin!"
echo ""
echo "  Configuration files:"
echo "    .env                — environment variables"
echo "    etebase-server.ini  — server config (domain, database)"
echo ""
echo "  To change the domain or other settings, edit etebase-server.ini"
echo "  and restart: docker compose restart server"
echo ""
