package io.silentsuite.sync.ui.setup

import android.app.Application
import java.util.UUID

/** Process-scoped evidence for [RegistryProcessBoundaryRuntimeTest]; nothing here survives a process. */
object RegistryProcessBoundaryProbe {
    const val RUNNER_ARGUMENT = "registryBoundaryProbe"

    /** Regenerated by every process: a reader that sees the writer's value is not a fresh process. */
    val processNonce: String = UUID.randomUUID().toString()

    /** Production registry read taken before Application.onCreate; null unless the lane opted in. */
    @Volatile var beforeLaunch: AccountCreationRegistry.ReadResult? = null
        private set

    /**
     * Called by the instrumentation runner before Application.onCreate, so launch reconciliation
     * cannot change what this fresh process first loaded from disk through the production store.
     */
    fun captureBeforeLaunch(app: Application) {
        check(PostLoginStartupChecks.snapshot().launchOutcome == null) { "Launch bootstrap already ran" }
        beforeLaunch = AccountCreationRegistry.open(app).readResult()
    }
}
