package io.silentsuite.sync.ui.setup

import android.app.Application
import android.content.Context
import java.util.UUID

/** Process-scoped evidence for [RegistryProcessBoundaryRuntimeTest]; nothing here survives a process. */
object RegistryProcessBoundaryProbe {
    const val RUNNER_ARGUMENT = "registryBoundaryProbe"

    /**
     * Content-free shape of the stored registry value: never its contents, rows or length. A reader
     * cannot observe the shape a fresh process loaded once launch reconciliation has rewritten the
     * store, so the pre-bootstrap shape is captured here instead of asserted afterwards.
     */
    enum class Ending { ABSENT, NEWLINE_FREE, NEWLINE_TERMINATED, PADDED_FOUR_SPACES, OTHER }

    /** Regenerated by every process: a reader that sees the writer's value is not a fresh process. */
    val processNonce: String = UUID.randomUUID().toString()

    /** Production registry read taken before Application.onCreate; null unless the lane opted in. */
    @Volatile var beforeLaunch: AccountCreationRegistry.ReadResult? = null
        private set

    /** Shape of the same stored value at that moment; null unless the lane opted in. */
    @Volatile var beforeLaunchEnding: Ending? = null
        private set

    /**
     * Called by the instrumentation runner before Application.onCreate, so launch reconciliation
     * cannot change what this fresh process first loaded from disk through the production store.
     */
    fun captureBeforeLaunch(app: Application) {
        check(PostLoginStartupChecks.snapshot().launchOutcome == null) { "Launch bootstrap already ran" }
        beforeLaunchEnding = ending(app)
        beforeLaunch = AccountCreationRegistry.open(app).readResult()
    }

    /** Classifies the stored value as it is now; only the enum constant ever leaves this object. */
    fun ending(context: Context): Ending {
        val value = context.getSharedPreferences(PREFS, Context.MODE_PRIVATE).getString(KEY, null)
        return when {
            value == null -> Ending.ABSENT
            value.endsWith(PADDED_ENDING) -> Ending.PADDED_FOUR_SPACES
            value.endsWith("\n") -> Ending.NEWLINE_TERMINATED
            value.endsWith(" ") || value.endsWith("\t") -> Ending.OTHER
            else -> Ending.NEWLINE_FREE
        }
    }

    private const val PREFS = "account_creation_registry"
    private const val KEY = "rows"
    private const val PADDED_ENDING = "\n    "
}
