
buildscript {
    ext.versions = [
        conscrypt: '2.5.3'
    ]
}

apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'

android {
    namespace 'at.bitfire.cert4android'
    compileSdkVersion rootProject.ext.compileSdkVersion

    defaultConfig {
        minSdkVersion 14            // Android 4.0
        targetSdkVersion 33
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    buildFeatures {
        dataBinding = true
        buildConfig = true
        aidl = true
    }
    lint {
        disable 'MissingTranslation', 'ExtraTranslation'
    }


    defaultConfig {
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
}

dependencies {
    def androidX = rootProject.ext.androidXVersions

    implementation "org.jetbrains.kotlin:kotlin-stdlib:${rootProject.ext.kotlin_version}"

    implementation "androidx.core:core:${androidX.core}"
    implementation "androidx.appcompat:appcompat:${androidX.appcompat}"
    implementation "androidx.cardview:cardview:${androidX.cardview}"
    implementation "androidx.lifecycle:lifecycle-livedata:${androidX.lifecycle}"
    implementation "androidx.lifecycle:lifecycle-viewmodel-ktx:${androidX.lifecycle}"
    implementation "com.google.android.material:material:${androidX.material}"
    implementation "org.conscrypt:conscrypt-android:${versions.conscrypt}"

    androidTestImplementation "androidx.test:runner:${androidX.testRunner}"
    androidTestImplementation "androidx.test:rules:${androidX.testRules}"
    androidTestImplementation 'com.squareup.okhttp3:mockwebserver:4.9.0'

    testImplementation 'junit:junit:4.13'
}
